annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: "External IP Webhook"
  catalog.cattle.io/namespace: cattle-externalip-system
  catalog.cattle.io/release-name: rancher-externalip-webhook
  catalog.cattle.io/ui-component: rancher-externalip-webhook
  catalog.cattle.io/os: linux
apiVersion: v1
description: |
  Deploy the externalip-webhook to mitigate k8s CVE-2020-8554
name: rancher-externalip-webhook
version: %VERSION%
appVersion: %APP_VERSION%
kubeVersion: '>=1.16.0-0'
home: https://github.com/rancher/externalip-webhook
sources:
  - https://github.com/rancher/externalip-webhook
engine: gotpl
maintainers:
- name: rawmind0
  email: raul@rancher.com
keywords:
- cve
- externalip
- webhook
- security
