resources:
- webhook.yaml
- service.yaml
- manifests.yaml

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: webhook
  newName: test
